### ISSUE TITLE
Create Solr query grammar parser

### ISSUE THREAD

**Issue by Sciumo** [Sciumo/myna-parser#1]
Create an AST parser for Solr query grammar to include the pluggable parser specifically spatial.

https://wiki.apache.org/solr/SolrQuerySyntax
https://wiki.apache.org/solr/SpatialSearch

**Comment by denim2x** [comment]
I'd like to help out with this

**Comment by Sciumo** [comment]
There is a [Bountysource Bounty](https://www.bountysource.com/issues/45107821-create-solr-query-grammar-parser) on this issue.
@cdiggins has started the bounty and I'll close this issue here once the parser is committed.

**Comment by cdiggins** [comment]
Hi @Sciumo,

Here are links to the new Lucene grammar and parser with tests:

- https://github.com/cdiggins/myna-parser/blob/master/gramma7rs/grammar_lucene.js
- https://github.com/cdiggins/myna-parser/blob/master/tests/test_lucene.js 
- https://cdiggins.github.io/myna-parser/tests/qunit.html

**Comment by Sciumo** [comment]
Fixed by 6df2d48506ac7b83e7344c1ddf4b7507a4b3e3e3
